### ISSUE TITLE
Persistent history

### ISSUE THREAD

**Issue by daniele77** [daniele77/cli#39]
It would be useful to (optionally) make persistent the cli history.

The local session and each remote session should maintain its own history.
But how to identify remote sessions?
According to the client IP address?
Or more simply by providing one history for the local session and just one for all the remote sessions? In this case, what happens when more than one client is connected simultaneously?

Maybe we could start by providing persistent history just for the local session.

**Comment by vrobles-gee** [comment]
Hi @daniele77, I was wondering if you ever started to work on this feature. It would be really useful for our use case (we are using remote sessions on telnet server). About the question "what happens when more than one client is connected simultaneously", I am not sure how does SSH manages it, but maybe the same behavior can be duplicated?.

**Comment by daniele77** [comment]
@vrobles-gee I will start as soon as possible with this issue, because it's relevant for our applications also. I'd like to copy the behavior of ssh/telnet.
BTW: in the future, I'd like to publish somewhere a list of known applications using this library. If you don't have privacy constraints, could you share publicly in what kind of application are you using cli? Thanks.

**Comment by daniele77** [comment]
After a couple of tests, ssh seems to save history data in a persistent way only after exiting the session. It seems there is only one persistent history, and each time a session is closed, its history data is appended to the history file. When a new session starts, the history file is loaded.

This will also be the behavior of the library.

**Comment by vrobles-gee** [comment]
@daniele77, that behavior seems good. 

I also wanted to ask how would this feature behave if we had Authentication feature (issue #57) in the future, and multiple credentials are supported? I believe persistent history would behave like you described but will store separated history file per user right?

About the application, we are using cli library to provide remote access to a network management software. I'm sorry I can't disclose more details due to privacy constraints as you said.

Thanks,

**Comment by daniele77** [comment]
The feature is almost completed (both with persistent history on a file and with in-memory history, as policies).

As for the authentication, see my answer on issue #57
